### ISSUE TITLE
Not working on Windows 10.

### ISSUE THREAD

**Issue by MrChriZ** [cyberponk/psubst#1]
I've tried both the original psubst and this one and it doesn't appear to be working under Windows 10.
It does create the substitution but as soon as the machine is restarted it disappears.

**Comment by cyberponk** [comment]
Hey Chriz, i´ll take a look as soon as possible! Thanks for the heads up!

**Comment by cyberponk** [comment]
Chriz, I have updated a new release that removes the need of the /P argument. Please check now.
You must have ADMIN rights to create a persistent mapping (prompt for admin rights is automatically shown if not already given). 

Please check and let me know if it works!

**Comment by DaveStLou** [comment]
Cyberponk, I am getting the following when I run the new version under Win10 no matter what I put in including /?: 

> The syntax of the command is incorrect.
> <!DOCTYPE html>

**Comment by cyberponk** [comment]
That is strange... You probably saved it with an incorrect encoding or you saved it as an HTML page.

Did you download the psubst.bat from the Releases tab? Please try it.
Then you have to run it from command prompt (not powershell).
Try it and let me know.

**Comment by DaveStLou** [comment]
I downloaded it again and all is good. Works great on Windows 10. Thanks!

**Comment by cyberponk** [comment]
Great to know! Cheers!
